### ISSUE TITLE
Many node types share the same color with this grammar

### ISSUE THREAD

**Issue by swrobel** [tree-sitter/tree-sitter-ruby#94] opened 2018-10-25 00:41 UTC
I appreciate that tree-sitter is faster & more efficient than the old grammar, but the change is a bit disappointing. Symbols, constants, numbers, and boolean values (`true/false`) are now all the same color with all of the built-in themes I've tried (Base16 Tomorrow Dark, Atom Dark, One Dark). 

Examples w/ Base16 Tomorrow Dark. Before:
<img width="484" alt="screen shot 2018-10-24 at 5 40 38 pm" src="https://user-images.githubusercontent.com/157270/47469097-f6879a80-d7b3-11e8-9ae2-190033f6c770.png">

Tree-sitter:
<img width="489" alt="screen shot 2018-10-24 at 5 40 25 pm" src="https://user-images.githubusercontent.com/157270/47469102-fab3b800-d7b3-11e8-8a54-a9a45f3cad63.png">

Was this intentional or is it just a WiP?

**Comment by maxbrunsfeld** [comment] 2018-10-25 00:49
It looks like I missed a class that's supposed to be applied to symbols.

Constant identifiers being the same color as constant literals is the expected behavior in most languages, but I guess we were doing something different in ruby? 

I'll push a fix tomorrow. It should be trivial; we just need to tweak the scope mappings specified [here](https://github.com/atom/language-ruby/blob/master/grammars/tree-sitter-ruby.cson#L151) and [here](https://github.com/atom/language-ruby/blob/master/grammars/tree-sitter-ruby.cson#L120).

**Comment by Ben3eeE** [comment] 2018-10-26 11:54
:wave: Sorry for the regression. This was fixed in https://github.com/atom/language-ruby/pull/244 and will go out in the next hotfix release. See the PR for details :slightly_smiling_face:

**Comment by rsese** [comment] 2018-11-02 18:17
Going to go ahead and close, I believe the fix is in the latest hotfix releases 1.32.1 and 1.33.0-beta1 which went out 2 days ago.

**Closed by rsese** 2018-11-02 18:17 UTC
